version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: sodai-backend
    ports:
      - "8000:8000"
    networks:
      - sodai-net

  frontend:
    build:
      context: ./frontend
    container_name: sodai-frontend
    ports:
      - "7860:7860"
    environment:
      BACKEND_URL: "http://backend:8000/predict"
    depends_on:
      - backend
    networks:
      - sodai-net

networks:
  sodai-net:
    driver: bridge
